carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),

]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^product/', include('products.urls', namespace="product")),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^cart/', include('carts.urls', namespace="cart")),
    url(r'^$', HomeView.as_view(), name='home'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product

User = settings.AUTH_USER_MODEL
# Create your models here.

class CartManager(models.Manager):
    #This function is used to create a new cart if it doesnot exist and cart is not created if the same cart exists
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        print(user)
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):

    user = models.ForeignKey(User, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=30, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=30, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) + Decimal(1.08) # total amount with added tax amount
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect

from account.forms import LoginForm, GuestForm
from account.models import GuestEmail
from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

# Create your views here.

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    #This is not efficient method for calculating total since it gets updated after storing in the database or let's say after loading two times
    # products = cart_obj.products.all()
    # total = 0
    # for x in products:
    #     total += x.price
    # print(total)
    # cart_obj.total = total
    # cart_obj.save()

    return render(request, "carts/home.html", {"cart":cart_obj})


def cart_update(request):
    print(request.POST)
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("error")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj) #products can also be added with the help of id as: cart_obj.products.add(1)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    
    user = request.user
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()
    guest_email_id = request.session.get("guest_email_id")
    
    if user.is_authenticated():
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)
    
    elif guest_email_id is not None:
        guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
        billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(email=guest_email_obj.email)
    
    else:
        pass
        
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form":guest_form,
    }
    return render(request, "carts/checkout.html", context)

carts/templates/carts/checkout.html
{% extends "base.html" %}
{% block content %}
{% if not billing_profile %}
    <div class="row text-center">
        <div class="col-12 col-md-6">
            <p class="lead">Login</p>
            {% include "accounts/snippets/form.html" with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-6">
            Continue as guest
            {% url "guest_register" as guest_register_url %}
            {% include "accounts/snippets/form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>

{% else %}
    <h1>Checkout</h1>
    <p>Cart Total = {{ object.cart.total }}</p>
    <p>Shipping Total = {{ object.shipping_total }}</p>
    <p>Order Total = {{ object.total }}</p>
{% endif %}


{% endblock content %}

carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>My Cart</h1>
    {% if cart.products.exists %}
        <table class="table">
          <thead>
            <tr>
                <th>S.N.</th>
              <th>Product Name</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            {% for product in cart.products.all %}
            <tr scope="row">
              <td>{{ forloop.counter }}</td>
              <td>
                  <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                  {% include "products/snippets/update-cart.html" with product=product cart=cart in_cart=True %}
              </td>
              <td>{{ product.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
              <td><b>Subtotal</b> {{ cart.subtotal }}</td>
            </tr>
            <tr>
              <td colspan="2"></td>
              <td><b>Total</b> {{ cart.total }}</td>
            </tr>
            <tr>
              <td colspan="2"></td>
              <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
            </tr>
          </tbody>
        </table>
    {% else %}
    <p class="lead">Cart is empty</p>
    {% endif %}
      </div>
{% endblock content %}