carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),

]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^product/', include('products.urls', namespace="product")),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^cart/', include('carts.urls', namespace="cart")),
    url(r'^$', HomeView.as_view(), name='home'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url
from .views import (
    SearchProductView
)

urlpatterns = [
    url(r'^$',SearchProductView.as_view(), name='query'),
]

search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
# Create your views here.


class SearchProductView(ListView):

    template_name = 'search/snippets/view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Product.objects.search(query)
        return Product.objects.featured()

search/templates/search/snippets/search-form.html
<form method="GET" class="form my-2 my-lg-0" action="{% url 'search:query' %}">
    <div class="input-group" >
        <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value="{{ request.GET.q }}">
        <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">Search</button>
        </span>
    </div>
</form>

search/templates/search/snippets/view.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row mb-3">
        {% if query %}
        <div class="col-12">
            Search result: {{ query }}
            <hr>
        </div>  
        {% else %}
        <div class="col-12 col-md-8 mx-auto py-5">
                {% include 'search/snippets/search-form.html' %}
        </div>
        <div class="col-12"><hr></div>
        {% endif %}
        
        {% for obj in object_list %}
            <div class="col col-sm-4">
                <div class="card">
                    <div class="card-header">
                        {% if obj.image  %}
                            <img src="{{obj.image.url}}" class="img-fluid"><br>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <div class="card-title">
                            <a href="{{ obj.get_absolute_url }}">{{obj.title}}</a>
                        </div>
                    </div> 
                    <div class="card-footer">{{obj.description|truncatewords:12}}</div>
                    {% if forloop.counter|divisibleby:3 %}
                        </div></div><div><hr></div>
                    {% else %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}